app:
  applicationId: xxXXXXXX-xXXX-xxXX-XXxX-xXXxxXXXXxXX
  env: Development
  host: ${APP_HOST:http://localhost:9000}
  redact:
    - ${CLIENT_ID}
    - ${PRIVATE_KEY}
  authentication:
    loggedInIndicator: "HTTP.*2[0-9][0-9]\\s*O[kK](\\s*)|HTTP.*3[0-9][0-9].*"
    loggedOutIndicator: "HTTP.*4[0-9][0-9](\\s*)Unauthorized.*"
    externalCommand:
      command: "yourScript.sh"
    testPath:
      path: /version
      fail: ".*302.*Location:.*/login.*"
    # Configure a custom script for session management
    sessionScript:
      # This session script runs an external sessionCommand on every request, which builds headers and cookies and
      #  returns them to the session script as a JSON blob like:
      #  https://docs.stackhawk.com/hawkscan/authenticated-scanning/external-command-authentication.html#expected-output-from-external-command
      #
      # sessionCommand's JSON is passed back up to the session script to be added to the request before sending.
      name: external-command-session.kts
      parameters:
        externalCommand: "../scripts/examples/session/session_script.sh"
        # inputData: ${INPUT_DATA:whatever} # Input data for the session script in whatever format it requires. JSON?
        client_id: "${CLIENT_ID}"
        private_key: "${PRIVATE_KEY}"
#-- StackHawk Pathing to Your Auth0 Script --
hawkAddOn:
  scripts:
      # This means the script should be in ../../scripts/examples/session/external-command-session.kts
    - name: external-command-session.kts
      type: session
      path: ../../scripts/examples
      language: KOTLIN
